---
- name: Create a new VM and configure dev services
  hosts: all

  tasks:
    - name: create the host
      redhat.satellite.host:
        username: "admin"
        password: "{{ sat6_password }}"
        server_url: "{{ sat6_url }}"
        name: "new_host"
        hostgroup: "Test Hosts"
        build: true
        state: present
        compute_attributes:
          cpus: 1
          memory_mb: 2048
          start: "1"
