---
- name: Create a new VM and configure dev services
  hosts: all

  tasks:
    - name: create the host
      redhat.satellite.host:
        username: "admin"
        password: "{{ sat6_password }}"
        server_url: "{{ sat6_url }}"
        name: "newhost.rock.lab"
        hostgroup: "Test Hosts"
        build: true
        state: present
        compute_attributes:
          cpus: 1
          memory_mb: 2048
          start: "1"
        provision_method: image
        image: "Red Hat 8.3 KVM"
        compute_resource: "Rock Lab KVM Hypervisor"
        location: "Default Location"
        organization: "Default Organization"
        interfaces_attributes:
          - name: "newhost"
            type: "interface"
            primary: yes
            managed: yes
            provision: yes
            domain: "rock.lab"
            virtual: no
            subnet: "Libvirt subnet"
